In [ ]:
from deltalake import DeltaTable
from data_operators.api import APIClient
from data_operators.data_ingest import DataIngest
from data_operators.data_cleaner import DataCleaner
from data_operators.db import DB

In [ ]:

client = APIClient()
client.fetch_search(num_pages=2)
client.get_videos()
client.get_channels()
client.get_comments(max_comments_per_video=100)

Search pages: 100%|██████████| 2/2 [00:00<00:00,  2.14it/s]
Video batches: 100%|██████████| 2/2 [00:00<00:00,  2.32batch/s]
Channel batches: 100%|██████████| 2/2 [00:00<00:00,  3.45batch/s]
Comment threads: 100%|██████████| 99/99 [00:44<00:00,  2.23video/s]

In [ ]:

ingest = DataIngest()
for source in ["Search_Results", "Video_Details", "Channel_Details", "Comments"]:
    df = ingest.ingest(source)
    print(f"{source}: {df.shape}")

Search_Results: (100, 20)
Video_Details: (99, 20)
Channel_Details: (83, 23)
Comments: (10380, 21)

In [ ]:

DeltaTable("L1/Search_Results").to_pandas()

,kind,etag,video_kind,video_id,published_at,channel_id,title,description,channel_title,live_broadcast_content,publish_time,thumbnail_default_url,thumbnail_default_width,thumbnail_default_height,thumbnail_medium_url,thumbnail_medium_width,thumbnail_medium_height,thumbnail_high_url,thumbnail_high_width,thumbnail_high_height
0,youtube#searchResult,MIAJuQMZuqzmYysUa5Eqn01Ai1Y,youtube#video,xs_3YxHqaQw,2025-10-09T14:47:29Z,UCMhQN5zd6KzFyH_ny8xBbmA,iPhone 17 Pro Max durability test #iphone17ser...,,CamboFixing Shorts,none,2025-10-09T14:47:29Z,https://i.ytimg.com/vi/xs_3YxHqaQw/default.jpg,120,90,https://i.ytimg.com/vi/xs_3YxHqaQw/mqdefault.jpg,320,180,https://i.ytimg.com/vi/xs_3YxHqaQw/hqdefault.jpg,480,360
1,youtube#searchResult,UNgXc3_UhQDxOw5gEryWTHyA2po,youtube#video,FQy4D5LS2NQ,2025-10-10T15:25:08Z,UCaodVRLodyAeCiq23ahftGA,جبت iphone 17 pro!!!,,Farah Roushdy,none,2025-10-10T15:25:08Z,https://i.ytimg.com/vi/FQy4D5LS2NQ/default.jpg,120,90,https://i.ytimg.com/vi/FQy4D5LS2NQ/mqdefault.jpg,320,180,https://i.ytimg.com/vi/FQy4D5LS2NQ/hqdefault.jpg,480,360
2,youtube#searchResult,rwbx6jS1XugqlACt5Mw7jjXGyU4,youtube#video,rng_yUSwrgU,2025-10-01T20:41:40Z,UCBJycsmduvYEL83R_U4JriQ,iPhone 17 Review: No Asterisks!,This is the best iPhone in years. Which can ha...,Marques Brownlee,none,2025-10-01T20:41:40Z,https://i.ytimg.com/vi/rng_yUSwrgU/default.jpg,120,90,https://i.ytimg.com/vi/rng_yUSwrgU/mqdefault.jpg,320,180,https://i.ytimg.com/vi/rng_yUSwrgU/hqdefault.jpg,480,360
3,youtube#searchResult,pocHG6tz1S6UFuPD0uV5S4gBN5s,youtube#video,qUuXxqY5RXU,2025-09-23T15:32:48Z,UCVJMlu9ObMGjDBkpTZkwpRg,iPhone 17 Pro Max - iPhone Air - iPhone 17 || ...,YehiaRadwan #يحيى_رضوان أنطباعاتي الأولية عن ا...,Yehia Radwan يحيى رضوان,none,2025-09-23T15:32:48Z,https://i.ytimg.com/vi/qUuXxqY5RXU/default.jpg,120,90,https://i.ytimg.com/vi/qUuXxqY5RXU/mqdefault.jpg,320,180,https://i.ytimg.com/vi/qUuXxqY5RXU/hqdefault.jpg,480,360
4,youtube#searchResult,lo4giS8xYUQqYQvUWlXb56Gcyi4,youtube#video,S1NpcOjKBio,2025-09-19T16:59:26Z,UCxboM7lRXcb_-lePSScA_qg,Unboxin the iPhone 17 Pro Max in Cosmic Orange...,,My Mini Bakes,none,2025-09-19T16:59:26Z,https://i.ytimg.com/vi/S1NpcOjKBio/default.jpg,120,90,https://i.ytimg.com/vi/S1NpcOjKBio/mqdefault.jpg,320,180,https://i.ytimg.com/vi/S1NpcOjKBio/hqdefault.jpg,480,360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,youtube#searchResult,Xg8gIVgzGuI1UTDoSJ1Ha4fzE5Q,youtube#video,m5XsOIrcLLE,2025-09-20T12:46:19Z,UCrSYpOSIORd5AELgl8_xSiA,Unboxing IPhone 17 Pro 🧡 #rajanadkat #youtubes...,,RAJ ANADKAT,none,2025-09-20T12:46:19Z,https://i.ytimg.com/vi/m5XsOIrcLLE/default.jpg,120,90,https://i.ytimg.com/vi/m5XsOIrcLLE/mqdefault.jpg,320,180,https://i.ytimg.com/vi/m5XsOIrcLLE/hqdefault.jpg,480,360
96,youtube#searchResult,zhAjm7wIWOGMokuEW5gKoXjPPnM,youtube#video,jAiki0GOrFA,2025-09-21T10:47:56Z,UCglXlpWjIi95auM3umWWLdw,हमने किया Apple iPhone 17 Air का Bend Test📲 #s...,हमने किया Apple iphone 17 Air का Bend Test S...,Tech Master,none,2025-09-21T10:47:56Z,https://i.ytimg.com/vi/jAiki0GOrFA/default.jpg,120,90,https://i.ytimg.com/vi/jAiki0GOrFA/mqdefault.jpg,320,180,https://i.ytimg.com/vi/jAiki0GOrFA/hqdefault.jpg,480,360
97,youtube#searchResult,fXFj676HH9YB0sFdV4Y2FxwhbFI,youtube#video,SyRmmtNZ_vw,2026-02-16T15:28:50Z,UC8IPcF4sxZt1TCs7la4EYtw,5 Meses con el iPhone 17 - ¿Me arrepiento?,Hazte miembro del canal y recibe estos emojis:...,Domingo Gomes,none,2026-02-16T15:28:50Z,https://i.ytimg.com/vi/SyRmmtNZ_vw/default.jpg,120,90,https://i.ytimg.com/vi/SyRmmtNZ_vw/mqdefault.jpg,320,180,https://i.ytimg.com/vi/SyRmmtNZ_vw/hqdefault.jpg,480,360
98,youtube#searchResult,RQfF_DGH5EFQ3x-vDCI1KwD5daI,youtube#video,Jd8SC-OgOGo,2025-09-12T21:11:56Z,UC3iwxKMRg5l2aDG_8XK2nSQ,The iPhone 17 Pro 📲 #TheManniiShow.com/series,"WEBBY AWARDS Honoree x2!! ""MJ's WORLD!"" @TheMa...",The Mannii Show,none,2025-09-12T21:11:56Z,https://i.ytimg.com/vi/Jd8SC-OgOGo/default.jpg,120,90,https://i.ytimg.com/vi/Jd8SC-OgOGo/mqdefault.jpg,320,180,https://i.ytimg.com/vi/Jd8SC-OgOGo/hqdefault.jpg,480,360
99,youtube#searchResult,bmdcJT7VGaCztLvwWJtYyqJvs44,youtube#video,clpAfuR7J7E,2025-09-26T05:16:11Z,UC20sXo8ReewkzNKBFgzVCPA,😱உண்மையான Powerhouse எது❓ 👊🏻 iPhone 16 Pro 🆚 ...,"Planning to buy a new iPhone? In this video, w...",Tamil Tech - MrTT,none,2025-09-26T05:16:11Z,https://i.ytimg.com/vi/clpAfuR7J7E/default.jpg,120,90,https://i.ytimg.com/vi/clpAfuR7J7E/mqdefault.jpg,320,180,https://i.ytimg.com/vi/clpAfuR7J7E/hqdefault.jpg,480,360

In [4]:
DeltaTable("L1/Video_Details").to_pandas()

,video_id,kind,etag,published_at,channel_id,title,description,category_id,thumbnail_default_url,thumbnail_medium_url,thumbnail_high_url,duration,aspect_ratio,view_count,like_count,dislike_count,favorite_count,comment_count,upload_status,privacy_status
0,8v6wQJWPkEQ,youtube#video,h3ENxqORBRF4PpwaPPZPwwhVDkk,2026-07-04T13:57:33Z,UCiIvTccEUH5EzHVfEi3_xeA,iPhone 17 Pro Max Cosmic Orange📱🔥#noads #tikto...,,24,https://i.ytimg.com/vi/8v6wQJWPkEQ/default.jpg,https://i.ytimg.com/vi/8v6wQJWPkEQ/mqdefault.jpg,https://i.ytimg.com/vi/8v6wQJWPkEQ/hqdefault.jpg,PT11S,None,82018,547,None,0,8,processed,public
1,Dws2PxWKUx8,youtube#video,NbEJNdtnya0Yp5u6UppIX9HfLf4,2025-09-10T15:13:04Z,UCdoDYkupTElV62K7ttA_E4w,iPhone 17 PRICE in India ! *Value for Money* #...,#TechBar #India #Hindi #Apple #iPhone #iphone1...,28,https://i.ytimg.com/vi/Dws2PxWKUx8/default.jpg,https://i.ytimg.com/vi/Dws2PxWKUx8/mqdefault.jpg,https://i.ytimg.com/vi/Dws2PxWKUx8/hqdefault.jpg,PT51S,None,2555967,86242,None,0,852,processed,public
2,rng_yUSwrgU,youtube#video,YP7xU5pgH0KQoWOjBa1LKezbwj4,2025-10-01T20:41:40Z,UCBJycsmduvYEL83R_U4JriQ,iPhone 17 Review: No Asterisks!,This is the best iPhone in years. Which can ha...,28,https://i.ytimg.com/vi/rng_yUSwrgU/default.jpg,https://i.ytimg.com/vi/rng_yUSwrgU/mqdefault.jpg,https://i.ytimg.com/vi/rng_yUSwrgU/hqdefault.jpg,PT11M20S,None,6195306,168737,None,0,5693,processed,public
3,zuQNSmmrMwQ,youtube#video,MyKqvGnXpopTLLUNSFtSMPb4fIE,2025-09-27T14:01:41Z,UCHMXQSLdXL7q1SntZBjhW3Q,iPhone 17 vs iPhone 16 camera test 🔥,,22,https://i.ytimg.com/vi/zuQNSmmrMwQ/default.jpg,https://i.ytimg.com/vi/zuQNSmmrMwQ/mqdefault.jpg,https://i.ytimg.com/vi/zuQNSmmrMwQ/hqdefault.jpg,PT19S,None,1783453,12621,None,0,29,processed,public
4,lar6fS1-jXs,youtube#video,JfQqxau3NKiKYN9QgJWHJP_hMdY,2026-03-07T08:29:24Z,UCGfluwZUeQNG5HvHuKfSKgw,Galaxy S26 is BEATING the iPhone 17 - Like HOW 😂,,26,https://i.ytimg.com/vi/lar6fS1-jXs/default.jpg,https://i.ytimg.com/vi/lar6fS1-jXs/mqdefault.jpg,https://i.ytimg.com/vi/lar6fS1-jXs/hqdefault.jpg,PT1M12S,None,2179825,87264,None,0,1555,processed,public
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,109cc9GH5mE,youtube#video,3qppnv_t_ltk40_YjDrCjQ3RWMM,2025-10-16T02:22:23Z,UCz1404hPpQ65wzXdX2UywJg,iPhone 17 Pro Max vs iPhone 1 Similarities,,22,https://i.ytimg.com/vi/109cc9GH5mE/default.jpg,https://i.ytimg.com/vi/109cc9GH5mE/mqdefault.jpg,https://i.ytimg.com/vi/109cc9GH5mE/hqdefault.jpg,PT20S,None,10172367,58049,None,0,585,processed,public
95,gICkJ1tBr6E,youtube#video,7tL4sG1gjdBv6wbAVc5P34IS70M,2026-07-02T15:38:46Z,UCdoDYkupTElV62K7ttA_E4w,Don't BUY WRONG iPhone in 2026 *BIG MISTAKE*,Thinking about upgrading your phone during the...,28,https://i.ytimg.com/vi/gICkJ1tBr6E/default.jpg,https://i.ytimg.com/vi/gICkJ1tBr6E/mqdefault.jpg,https://i.ytimg.com/vi/gICkJ1tBr6E/hqdefault.jpg,PT11M30S,None,204494,5012,None,0,314,processed,public
96,jAiki0GOrFA,youtube#video,8jBHq-gK5lqCNg8LQdmdb5MdU0I,2025-09-21T10:47:56Z,UCglXlpWjIi95auM3umWWLdw,हमने किया Apple iPhone 17 Air का Bend Test📲 #s...,हमने किया Apple iphone 17 Air का Bend Test📲\n\...,28,https://i.ytimg.com/vi/jAiki0GOrFA/default.jpg,https://i.ytimg.com/vi/jAiki0GOrFA/mqdefault.jpg,https://i.ytimg.com/vi/jAiki0GOrFA/hqdefault.jpg,PT57S,None,32743960,632272,None,0,5528,processed,public
97,BU9gKr1miS8,youtube#video,iylnjB6xKM8espTDbn2N8CJfLFw,2025-09-17T12:00:31Z,UCMiJRAwDNSNzuYeN2uWa0pA,iPhone 17/Air/Pro Unboxing - What Apple didn't...,Testing all the things that we couldn't test b...,28,https://i.ytimg.com/vi/BU9gKr1miS8/default.jpg,https://i.ytimg.com/vi/BU9gKr1miS8/mqdefault.jpg,https://i.ytimg.com/vi/BU9gKr1miS8/hqdefault.jpg,PT16M24S,None,6414530,136883,None,0,6125,processed,public
98,-efhZ5tibzg,youtube#video,izL-V7p3KfoOI59cN22vf_57Yqg,2025-10-12T15:19:15Z,UCggKidH56IZIGQ8SppxYn-Q,NEW iPhone 17 purple 💜 unboxing Apple iPhone,NEW iPhone 17 purple 💜 iPhone case and screen...,26,https://i.ytimg.com/vi/-efhZ5tibzg/default.jpg,https://i.ytimg.com/vi/-efhZ5tibzg/mqdefault.jpg,https://i.ytimg.com/vi/-efhZ5tibzg/hqdefault.jpg,PT17S,None,3058751,42726,None,0,702,processed,public

In [5]:
DeltaTable("L1/Channel_Details").to_pandas()

,channel_id,kind,etag,title,description,custom_url,published_at,country,thumbnail_default_url,thumbnail_default_width,...,thumbnail_medium_height,thumbnail_high_url,thumbnail_high_width,thumbnail_high_height,likes_playlist,uploads_playlist,view_count,subscriber_count,hidden_subscriber_count,video_count
0,UCrMEAG9T3OZXqLixW45FmJQ,youtube#channel,PJP4PqbjMW-eE72jG3LLNJJI6_o,Rjey Tech,My name is Rjey and I make videos about techno...,@rjeytech,2006-06-17T01:19:28Z,CA,https://yt3.ggpht.com/ytc/AIdro_lANIfSG04-89X_...,88,...,240,https://yt3.ggpht.com/ytc/AIdro_lANIfSG04-89X_...,800,800,,UUrMEAG9T3OZXqLixW45FmJQ,45704360,80100,False,772
1,UCXc2ZhgmBumZfpmapT-VsGQ,youtube#channel,6UM40xwp0QAipwayXrRGhYEPgvY,Brofone,Hello!\nShare my creativity with you. Let's jo...,@brofone,2024-09-03T05:34:18.496276Z,NaN,https://yt3.ggpht.com/44pQZnyBs3nWSl7YnI_7QOBt...,88,...,240,https://yt3.ggpht.com/44pQZnyBs3nWSl7YnI_7QOBt...,800,800,,UUXc2ZhgmBumZfpmapT-VsGQ,4018715,18600,False,20
2,UCPExFH_AvloNX8FW68ihCLA,youtube#channel,gMyVzEYhAfzWu96g9-Oo1m_xW-8,Hope Clarke,"welcome to my channel 💐\ni post beauty, lifest...",@beachblondemermaid,2024-11-21T03:11:45.355214Z,NaN,https://yt3.ggpht.com/xJqX2RItZbo4_sttGJwLKdXI...,88,...,240,https://yt3.ggpht.com/xJqX2RItZbo4_sttGJwLKdXI...,800,800,,UUPExFH_AvloNX8FW68ihCLA,173117233,225000,False,734
3,UCDJMUQ5hdAxGYPz7yt4paNQ,youtube#channel,gQyRonDbu04ITASQM_nry5bAqkY,Caleon Twins,We're Samantha and Madeleine and we're Identic...,@caleontwins,2015-01-23T17:20:25Z,CA,https://yt3.ggpht.com/uT_U3OiNrH96i1cgWz_pdzcs...,88,...,240,https://yt3.ggpht.com/uT_U3OiNrH96i1cgWz_pdzcs...,800,800,,UUDJMUQ5hdAxGYPz7yt4paNQ,29501067,327000,False,693
4,UCq1xDLvVEIG3qLgDPGfgK5A,youtube#channel,Nn_CX1SlK1OgupEEXEItXnei8iU,NetSpeed7,🎥 IShowSpeed Edits ⚡⚡️\n\n🎬 Editing App: Capcu...,@netspeed7,2019-11-20T14:08:47.6832Z,PH,https://yt3.ggpht.com/UzqJVFQmqkwPWnBWsh9o0YKs...,88,...,240,https://yt3.ggpht.com/UzqJVFQmqkwPWnBWsh9o0YKs...,800,800,,UUq1xDLvVEIG3qLgDPGfgK5A,333191488,233000,False,155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,UCvK-hgzYbTKv-ELc4-H3FnA,youtube#channel,r1SuEL5RweR0j3pgDA4jv6jn2F4,Pebblu,📱 Pebblu Phone Mini 📱\nAvailable NOW!!,@pebbluphone,2025-05-12T00:44:48.903274Z,NaN,https://yt3.ggpht.com/MryH3B51LXtmeGECUXMFmmz7...,88,...,240,https://yt3.ggpht.com/MryH3B51LXtmeGECUXMFmmz7...,800,800,,UUvK-hgzYbTKv-ELc4-H3FnA,27048103,156000,False,227
79,UC8IPcF4sxZt1TCs7la4EYtw,youtube#channel,3uyKUECHGlqKx-LNlbUDAgjFRyI,Domingo Gomes,Me gustan los tacos🌮 y la Tecnología.,@new3sc,2016-07-05T21:03:44Z,US,https://yt3.ggpht.com/_4fuBwXLZcF3T8AIysQfaFMQ...,88,...,240,https://yt3.ggpht.com/_4fuBwXLZcF3T8AIysQfaFMQ...,800,800,,UU8IPcF4sxZt1TCs7la4EYtw,484075757,1330000,False,1100
80,UC3SafDS4jxWKROqzPaON0lA,youtube#channel,azVCk6Y12bwB5kMl2pHU9KFjRgg,MaybeHeilly,just a girl with a love for coffee & phone cas...,@maybeheilly,2015-07-19T07:53:56Z,US,https://yt3.ggpht.com/SFcTJWMcWuQ96C_BPzmiHrwX...,88,...,240,https://yt3.ggpht.com/SFcTJWMcWuQ96C_BPzmiHrwX...,800,800,,UU3SafDS4jxWKROqzPaON0lA,396968296,704000,False,1212
81,UC0MYNOsIrz6jmXfIMERyRHQ,youtube#channel,wyHRHB5A3sCyNz8frH7hMn4e7zM,Karl Conrad,Keeping things simple by doing what I love. te...,@karlconrad,2012-10-10T17:25:05Z,CA,https://yt3.ggpht.com/ytc/AIdro_n7S27L74hV5uI9...,88,...,240,https://yt3.ggpht.com/ytc/AIdro_n7S27L74hV5uI9...,800,800,,UU0MYNOsIrz6jmXfIMERyRHQ,393562894,1000000,False,1931
82,UCCiGY0qGJ6ArOh8FpwgmxJQ,youtube#channel,psF8sDc5WxZ0GfWMQBAi3ZXNHWE,ryan,I'm 20\nBUSINESS EMAIL: ryelists@gmail.com\n,@ryetechh,2021-09-14T01:51:37.576954Z,NaN,https://yt3.ggpht.com/NllxevCfOjNsPYLrjcwV7eXI...,88,...,240,https://yt3.ggpht.com/NllxevCfOjNsPYLrjcwV7eXI...,800,800,,UUCiGY0qGJ6ArOh8FpwgmxJQ,95716839,66500,False,1197

In [6]:
DeltaTable("L1/Comments").to_pandas()

,thread_id,kind,etag,video_id,channel_id,can_reply,total_reply_count,is_public,comment_id,comment_kind,...,text_display,text_original,author_display_name,author_profile_image_url,author_channel_url,author_channel_id,like_count,published_at,updated_at,parent_comment_id
0,UgyTKuFjNiiLbHrzbSR4AaABAg,youtube#commentThread,hGtKV7cBTkeSn55OUfloOsmAjdg,-JH1V8cbAXo,UCH1U2zpZGve5o116OXr-Zsw,True,0.0,True,UgyTKuFjNiiLbHrzbSR4AaABAg,youtube#comment,...,isnt the point of life to do things,isnt the point of life to do things,@namreblis,https://yt3.ggpht.com/wOu0UdTtWNO5BLRynYik4V4P...,http://www.youtube.com/@namreblis,UCHgAaxIecpVjlo_Gcc_XG0g,0,2026-06-20T05:18:23Z,2026-06-20T05:18:23Z,NaN
1,UgzD2pCBujPBWjTya6R4AaABAg,youtube#commentThread,ccGTVTRZAI3j6ASiLeRmqTmVHK4,-JH1V8cbAXo,UCH1U2zpZGve5o116OXr-Zsw,True,0.0,True,UgzD2pCBujPBWjTya6R4AaABAg,youtube#comment,...,Gorl shut up,Gorl shut up,@VspMalek,https://yt3.ggpht.com/74dGGCOos-cT1fzZbpFvCoQ5...,http://www.youtube.com/@VspMalek,UCSb3sQ7jsce5i42TiWRTe9w,0,2026-06-15T16:03:59Z,2026-06-15T16:03:59Z,NaN
2,UgwGnUcbIvZQ_jvEJjF4AaABAg,youtube#commentThread,d3gxkv0IGqxbqlod6XuRJyRuaho,-JH1V8cbAXo,UCH1U2zpZGve5o116OXr-Zsw,True,0.0,True,UgwGnUcbIvZQ_jvEJjF4AaABAg,youtube#comment,...,I have the lavender cause I always have black,I have the lavender cause I always have black,@RoyceIsraelFernandez,https://yt3.ggpht.com/nMeasVWah-kEArh1YHvEfiFV...,http://www.youtube.com/@RoyceIsraelFernandez,UCcDjex8i9-IqEkeWMyBDpjA,0,2026-06-06T22:59:13Z,2026-06-06T22:59:13Z,NaN
3,UgwyPkjd6gvP_Iw38494AaABAg,youtube#commentThread,sVlEnC5M2e3LIS1wO59ZsTXYSLo,-JH1V8cbAXo,UCH1U2zpZGve5o116OXr-Zsw,True,0.0,True,UgwyPkjd6gvP_Iw38494AaABAg,youtube#comment,...,Alguém pode me dar o nome da música? 😭 ❤️ Agor...,Alguém pode me dar o nome da música? 😭 ❤️ Agor...,@SorvettedeBaunilha,https://yt3.ggpht.com/07v4-gQfvOAM4g7NDaQGg_sX...,http://www.youtube.com/@SorvettedeBaunilha,UC4ejPj-EfGCFEbP_DMMlMgg,0,2026-06-06T17:18:23Z,2026-06-06T17:22:09Z,NaN
4,UgyVbY1S0YD_4hFGro94AaABAg,youtube#commentThread,Bx-qtYnDVE9OBwTmxX-HDQAmI7Y,-JH1V8cbAXo,UCH1U2zpZGve5o116OXr-Zsw,True,0.0,True,UgyVbY1S0YD_4hFGro94AaABAg,youtube#comment,...,I trade in my base iPhone 16 for the base 17 w...,I trade in my base iPhone 16 for the base 17 w...,@Gabriel_nattylifter1,https://yt3.ggpht.com/FZcaTqs0cboNXA9tuepBPfbs...,http://www.youtube.com/@Gabriel_nattylifter1,UCIL4IRhKeZS3xkVIRQrprgw,0,2026-05-13T22:52:00Z,2026-05-13T22:52:00Z,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10375,Ugy93bN02gS_Rv2urS54AaABAg,youtube#commentThread,zNk2ws3rSNXjO6UngV4Nu-5Ooak,zuQNSmmrMwQ,UCHMXQSLdXL7q1SntZBjhW3Q,True,0.0,True,Ugy93bN02gS_Rv2urS54AaABAg,youtube#comment,...,pizza dine in lena hai or online lena hai ...?...,pizza dine in lena hai or online lena hai ...?...,@chinnuwold,https://yt3.ggpht.com/Mb2H9mss87pxJD6FGaIeN-w9...,http://www.youtube.com/@chinnuwold,UCjLS5Bcpq2-bueRKRgcIRYQ,22,2025-10-08T19:43:32Z,2025-10-08T19:43:32Z,NaN
10376,UgwQKc_DjF2XScbztKl4AaABAg,youtube#commentThread,zO7F70wiUWbkoFRGBQXDdsKkUZ8,zuQNSmmrMwQ,UCHMXQSLdXL7q1SntZBjhW3Q,True,0.0,True,UgwQKc_DjF2XScbztKl4AaABAg,youtube#comment,...,2x mein iphone 16 looks more natural and in 1x...,2x mein iphone 16 looks more natural and in 1x...,@IkshitNandal0207,https://yt3.ggpht.com/XEx3HCwIbEbuRSqrsfE62fMy...,http://www.youtube.com/@IkshitNandal0207,UCvWfXtB8AbCPJtfM5kE_Y8A,24,2025-10-04T07:05:21Z,2025-10-04T07:05:21Z,NaN
10377,Ugyd02w3d_b__XlS9M14AaABAg,youtube#commentThread,kFBQsv7tK95MSF_JA9mGeOQGsDw,zuQNSmmrMwQ,UCHMXQSLdXL7q1SntZBjhW3Q,True,0.0,True,Ugyd02w3d_b__XlS9M14AaABAg,youtube#comment,...,Good job,Good job,@muhammaddickyhartanto2806,https://yt3.ggpht.com/7J1wfvge_LAvRjDzXOHSZqt3...,http://www.youtube.com/@muhammaddickyhartanto2806,UCExxR5OPhmZ9k4ECMcvEMpA,2,2025-09-28T05:12:19Z,2025-09-28T05:12:19Z,NaN
10378,Ugz0Ehcxa-U_h8P6WxJ4AaABAg,youtube#commentThread,tGQWAPOkWp3WDUwGwxpsOZvKyRI,zuQNSmmrMwQ,UCHMXQSLdXL7q1SntZBjhW3Q,True,1.0,True,Ugz0Ehcxa-U_h8P6WxJ4AaABAg,youtube#comment,...,Gangadhar hi saktimaan hai,Gangadhar hi saktimaan hai,@PranjalRoy30,https://yt3.ggpht.com/mZeqVhM8SBLRvrY7X01bpT_a...,http://www.youtube.com/@PranjalRoy30,UCRuDR3ymhG8GIEQae-SJ2wQ,45,2025-09-27T15:27:38Z,2025-09-27T15:27:38Z,NaN
10379,Ugz0Ehcxa-U_h8P6WxJ4AaABAg,youtube#comment,TT3qnLmGsKcGTY3uF2WUBk0H8Uk,zuQNSmmrMwQ,UCHMXQSLdXL7q1SntZBjhW3Q,None,NaN,None,Ugz0Ehcxa-U_h8P6WxJ4AaABAg.AN_aHiWfCBqAOT6-maKN6Y,youtube#comment,...,Nhi nhi Shaktimaan hi Gangadhar hai 😂,Nhi nhi Shaktimaan hi Gangadhar hai 😂,@teddyisangry6459,https://yt3.ggpht.com/0U2OmuEUhoTVOXZVZkKkwwA0...,http://www.youtube.com/@teddyisangry6459,UCB9FS3b6ADlY3SkADfI3_QQ,3,2025-10-19T14:11:01Z,2025-10-19T14:11:01Z,Ugz0Ehcxa-U_h8P6WxJ4AaABAg

In [ ]:

cleaner = DataCleaner()
videos = cleaner.clean_videos()
comments = cleaner.transform_comments()

Dropped 0 duplicate videos and 4 videos with missing fields.
Dropped 0 duplicate comments, 0 comments with missing fields, and 396 orphaned comments.

In [8]:
DeltaTable("L2/Video_Details").to_pandas()

,video_id,published_at,channel_id,title,description,category_id,view_count,like_count,dislike_count,comment_count,privacy_status,channel,fetched_comments_count
0,8v6wQJWPkEQ,2026-07-04T13:57:33Z,UCiIvTccEUH5EzHVfEi3_xeA,iPhone 17 Pro Max Cosmic Orange📱🔥#noads #tikto...,,24,82018,547,None,8,public,Moksha_6_7,8
1,Dws2PxWKUx8,2025-09-10T15:13:04Z,UCdoDYkupTElV62K7ttA_E4w,iPhone 17 PRICE in India ! *Value for Money* #...,#TechBar #India #Hindi #Apple #iPhone #iphone1...,28,2555967,86242,None,852,public,TechBar,101
2,rng_yUSwrgU,2025-10-01T20:41:40Z,UCBJycsmduvYEL83R_U4JriQ,iPhone 17 Review: No Asterisks!,This is the best iPhone in years. Which can ha...,28,6195306,168737,None,5693,public,Marques Brownlee,105
3,zuQNSmmrMwQ,2025-09-27T14:01:41Z,UCHMXQSLdXL7q1SntZBjhW3Q,iPhone 17 vs iPhone 16 camera test 🔥,,22,1783453,12621,None,29,public,Dev,29
4,lar6fS1-jXs,2026-03-07T08:29:24Z,UCGfluwZUeQNG5HvHuKfSKgw,Galaxy S26 is BEATING the iPhone 17 - Like HOW 😂,,26,2179825,87264,None,1555,public,mobiscrub,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,109cc9GH5mE,2025-10-16T02:22:23Z,UCz1404hPpQ65wzXdX2UywJg,iPhone 17 Pro Max vs iPhone 1 Similarities,,22,10172367,58049,None,585,public,AnotherTech,102
91,gICkJ1tBr6E,2026-07-02T15:38:46Z,UCdoDYkupTElV62K7ttA_E4w,Don't BUY WRONG iPhone in 2026 *BIG MISTAKE*,Thinking about upgrading your phone during the...,28,204494,5012,None,314,public,TechBar,125
92,jAiki0GOrFA,2025-09-21T10:47:56Z,UCglXlpWjIi95auM3umWWLdw,हमने किया Apple iPhone 17 Air का Bend Test📲 #s...,हमने किया Apple iphone 17 Air का Bend Test📲\n\...,28,32743960,632272,None,5528,public,Tech Master,101
93,BU9gKr1miS8,2025-09-17T12:00:31Z,UCMiJRAwDNSNzuYeN2uWa0pA,iPhone 17/Air/Pro Unboxing - What Apple didn't...,Testing all the things that we couldn't test b...,28,6414530,136883,None,6125,public,Mrwhosetheboss,107
94,-efhZ5tibzg,2025-10-12T15:19:15Z,UCggKidH56IZIGQ8SppxYn-Q,NEW iPhone 17 purple 💜 unboxing Apple iPhone,NEW iPhone 17 purple 💜 iPhone case and screen...,26,3058751,42726,None,702,public,HappyDownloads,116

In [9]:
DeltaTable("L2/Comments").to_pandas()

,thread_id,video_id,comment_id,text_display,author_display_name,author_channel_id,like_count,published_at
0,UgyTKuFjNiiLbHrzbSR4AaABAg,-JH1V8cbAXo,UgyTKuFjNiiLbHrzbSR4AaABAg,isnt the point of life to do things,@namreblis,UCHgAaxIecpVjlo_Gcc_XG0g,0,2026-06-20T05:18:23Z
1,UgzD2pCBujPBWjTya6R4AaABAg,-JH1V8cbAXo,UgzD2pCBujPBWjTya6R4AaABAg,Gorl shut up,@VspMalek,UCSb3sQ7jsce5i42TiWRTe9w,0,2026-06-15T16:03:59Z
2,UgwGnUcbIvZQ_jvEJjF4AaABAg,-JH1V8cbAXo,UgwGnUcbIvZQ_jvEJjF4AaABAg,I have the lavender cause I always have black,@RoyceIsraelFernandez,UCcDjex8i9-IqEkeWMyBDpjA,0,2026-06-06T22:59:13Z
3,UgwyPkjd6gvP_Iw38494AaABAg,-JH1V8cbAXo,UgwyPkjd6gvP_Iw38494AaABAg,Alguém pode me dar o nome da música? 😭 ❤️ Agor...,@SorvettedeBaunilha,UC4ejPj-EfGCFEbP_DMMlMgg,0,2026-06-06T17:18:23Z
4,UgyVbY1S0YD_4hFGro94AaABAg,-JH1V8cbAXo,UgyVbY1S0YD_4hFGro94AaABAg,I trade in my base iPhone 16 for the base 17 w...,@Gabriel_nattylifter1,UCIL4IRhKeZS3xkVIRQrprgw,0,2026-05-13T22:52:00Z
...,...,...,...,...,...,...,...,...
9979,Ugy93bN02gS_Rv2urS54AaABAg,zuQNSmmrMwQ,Ugy93bN02gS_Rv2urS54AaABAg,pizza dine in lena hai or online lena hai ...?...,@chinnuwold,UCjLS5Bcpq2-bueRKRgcIRYQ,22,2025-10-08T19:43:32Z
9980,UgwQKc_DjF2XScbztKl4AaABAg,zuQNSmmrMwQ,UgwQKc_DjF2XScbztKl4AaABAg,2x mein iphone 16 looks more natural and in 1x...,@IkshitNandal0207,UCvWfXtB8AbCPJtfM5kE_Y8A,24,2025-10-04T07:05:21Z
9981,Ugyd02w3d_b__XlS9M14AaABAg,zuQNSmmrMwQ,Ugyd02w3d_b__XlS9M14AaABAg,Good job,@muhammaddickyhartanto2806,UCExxR5OPhmZ9k4ECMcvEMpA,2,2025-09-28T05:12:19Z
9982,Ugz0Ehcxa-U_h8P6WxJ4AaABAg,zuQNSmmrMwQ,Ugz0Ehcxa-U_h8P6WxJ4AaABAg,Gangadhar hi saktimaan hai,@PranjalRoy30,UCRuDR3ymhG8GIEQae-SJ2wQ,45,2025-09-27T15:27:38Z
9983,Ugz0Ehcxa-U_h8P6WxJ4AaABAg,zuQNSmmrMwQ,Ugz0Ehcxa-U_h8P6WxJ4AaABAg.AN_aHiWfCBqAOT6-maKN6Y,Nhi nhi Shaktimaan hi Gangadhar hai 😂,@teddyisangry6459,UCB9FS3b6ADlY3SkADfI3_QQ,3,2025-10-19T14:11:01Z

In [ ]:

db = DB()
db.load_from_L2()

Loaded 95 videos and 9984 comments into yt.db.